# Generated by Django 5.0.2 on 2024-10-30 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("media_condition", models.CharField(max_length=255)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("kept", models.BooleanField(default=False)),
                ("evaluated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LoserListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loser_listing",
                        to="processing.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discogs_id", models.CharField(max_length=255, unique=True)),
                ("artist", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("format", models.CharField(default="", max_length=255)),
                ("label", models.TextField()),
                ("catno", models.CharField(max_length=255, null=True)),
                ("wants", models.IntegerField(default=0)),
                ("haves", models.IntegerField(default=0)),
                ("added", models.DateTimeField(default=django.utils.timezone.now)),
                ("genres", models.JSONField(default=list)),
                ("styles", models.JSONField(default=list)),
                ("suggested_price", models.CharField(default="", max_length=255)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "ordering": ["-added"],
                "indexes": [
                    models.Index(fields=["-added"], name="processing__added_741c3f_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processing.record"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="processing.seller"
            ),
        ),
    ]
